version: "3.9"
services:
  srv:
    image: srv:shop
    restart: always
    volumes:
      - static:/app/static
  cli:
    image: cli:shop
    container_name: cli
    restart: always
    depends_on:
      - srv
  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    ports:
      - 7000:7000
      - 3000:3000
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - cli
volumes:
  static: null
