version: "3.9"
services:
  srv:
    image: srv:shop
    restart: always
  cli:
    image: cli:shop
    container_name: cli
    restart: always
    depends_on:
      - srv
  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:8000
      - 8080:8080
    depends_on:
      - cli
