export { default as MainCheckout } from './maincheckout'
export { default as MainGroups } from './maingroups'
export { default as MainLogin } from './mainlogin'
export { default as MainProductOne } from './mainproductone'
export { default as MainProducts } from './mainproducts'
export { default as MainProfile } from './mainprofile'
export { default as MainSubgroups } from './mainsubgroups'
